debug: false
server:
  port: 8083
  # 配置项目的访问路径
  servlet:
    context-path: /
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/a?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&autoReconnect=true&useSSL=false
    username: root
    password: root
  redis:
    cluster:
      nodes: 192.168.229.129:7000, 192.168.229.129:7001, 192.168.229.129:7002,
        192.168.229.129:7003, 192.168.229.129:7004, 192.168.229.129:7005
#  redis:
#    sentinel:
#      master: mymaster  # 哨兵监控的名称
#      nodes:
#        - 192.168.229.129:26379
#        - 192.168.229.129:26379 #哨兵的地址和端口号
# 单节点下的redis配置
#  redis:
#    host: 192.168.229.129
#    port: 6379
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
#  configuration:
#    map-underscore-to-camel-case: true #配置开启数据库驼峰匹配，也可以通过xml配置文件修改
#    cache-enabled: true #是否开启缓存
#    call-setters-on-nulls: true #指定当结果集中值为 null 的时候是否调用映射对象的 setter
  config-location: classpath:mybatis-config.xml #指定配置文件
# springboot默认采用的logback日志
#可以通过配置文件进行覆盖定制自己的日志，或者通过yml进行一些属性修改
#logging:
#  level:
#    root: info #指定了根目录的日志级别
#    com.dream.order: debug # 指定了自己的包日志级别
#  file: aa.log # 日志名字
#  path: ./ #指定日志打印到的文件
